/*
BSD 2-Clause License

Copyright (c) 2026, Alessandro Salerno and contributors

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <hera/graph.h>
#include <hera/svg.h>
#include <hera/util.h>

// NOTE: the following code was generated by Gemini CLI and is **totally
// experimental**

static ER_i32 layout_calculate_entity_layer(ER_GraphEntity *ent) {
    if (ent->gen_specifies == NULL) {
        return 0;
    }

    return 1 + layout_calculate_entity_layer(ent->gen_specifies);
}

// Get the height of the entire specialization subtree starting at ent
static ER_i32 layout_get_tree_height(ER_Graph *graph, ER_GraphEntity *ent) {
    ER_i32 max_child_h = 0;

    ER_GraphEntity *child;
    TAILQ_FOREACH(child, &ent->gen_specifiers, gen_link) {
        ER_i32 child_h = layout_get_tree_height(graph, child);
        max_child_h    = ER_MAX(max_child_h, child_h);
    }

    return ent->gen_h + (max_child_h > 0 ? 100 + max_child_h : 0);
}

void ER_layout_place(ER_Graph *graph) {
    ER_GraphRelation *rel, *tmp_rel;

    // Phase 1: Sizes and Layers
    ER_GraphEntity *ent, *tmp_ent;
    HASH_ITER(gen_hh, graph->gr_entities, ent, tmp_ent) {
        ent->gen_layer = layout_calculate_entity_layer(ent);
        ent->gen_w     = (ent->gen_astnode->ent_name.tok_value.str_len * 12) +
                     ER_SVG_ENTITY_W_PAD;
        ent->gen_h = ER_SVG_ENTITY_H_MIN;

        ER_ASTNode *attr;
        TAILQ_FOREACH(attr, &ent->gen_astnode->ent_attributes, an_link) {
            ER_ASTAttributeNode *atrn = (void *)attr;
            ER_i32 attr_w = (atrn->atr_name.tok_value.str_len * 10) +
                            ER_SVG_ENTITY_W_PAD;
            ent->gen_h += ER_SVG_ATTR_H_STEP;
            if (attr_w > ent->gen_w) {
                ent->gen_w = attr_w;
            }
        }
    }

    // Phase 2: Root-Tree Placement
    ER_i32 col_x[2] = {100, 1200}, col_y[2] = {100, 100};
    int    root_idx = 0;
    HASH_ITER(gen_hh, graph->gr_entities, ent, tmp_ent) {
        if (ent->gen_layer != 0) {
            continue;
        }

        int c        = root_idx % 2;
        ent->gen_col = c;
        ent->gen_x   = col_x[c];
        ent->gen_y   = col_y[c];
        col_y[c] += layout_get_tree_height(graph, ent) + 150;
        root_idx++;
    }

    // Recursive Child Placement
    for (ER_u8 l = 1; l < 5; l++) {
        HASH_ITER(gen_hh, graph->gr_entities, ent, tmp_ent) {
            if (ent->gen_layer != l) {
                continue;
            }

            ER_GraphEntity *p = ent->gen_specifies;
            ent->gen_col      = p->gen_col;
            ent->gen_x        = p->gen_x;
            ent->gen_y        = p->gen_y + p->gen_h + 100;

            // Shift siblings
            ER_GraphEntity *s, *ts;
            HASH_ITER(gen_hh, graph->gr_entities, s, ts) {
                if (s != ent && s->gen_specifies == p &&
                    s->gen_x >= ent->gen_x && s->gen_y == ent->gen_y) {
                    ent->gen_x = s->gen_x + s->gen_w + 50;
                }
            }
        }
    }

    // Phase 3: Relations (Center Column)
    ER_i32 rel_x = 650, rel_y_curr = 100;
    HASH_ITER(gre_hh, graph->gr_relations, rel, tmp_rel) {
        rel->gre_w = (rel->gre_astnode->rel_name.tok_value.str_len * 12) +
                     ER_SVG_RELATION_W_PAD;
        rel->gre_h = ER_SVG_RELATION_H_MIN;

        ER_ASTNode *attr;
        TAILQ_FOREACH(attr, &rel->gre_astnode->rel_attributes, an_link) {
            ER_ASTAttributeNode *atrn = (void *)attr;
            ER_i32 attr_w = (atrn->atr_name.tok_value.str_len * 10) +
                            ER_SVG_RELATION_W_PAD;
            rel->gre_h += ER_SVG_ATTR_H_STEP;
            if (attr_w > rel->gre_w) {
                rel->gre_w = attr_w;
            }
        }

        ER_i32        ay = 0, ec = 0;
        ER_GraphEdge *edge;
        TAILQ_FOREACH(edge, &rel->gre_edges, ged_link) {
            ay += edge->ged_entity->gen_y + edge->ged_entity->gen_h / 2;
            ec++;
        }

        ay         = (ec > 0) ? ay / ec : rel_y_curr;
        rel->gre_x = rel_x;
        rel->gre_y = ay - rel->gre_h / 2;
        if (rel->gre_y < rel_y_curr) {
            rel->gre_y = rel_y_curr;
        }
        rel_y_curr = rel->gre_y + rel->gre_h + 150;

        // Phase 4: Better Vertex Allocation and Surface Distribution
        ER_i32 v_used[4] = {0, 0, 0, 0}; // L, R, T, B
        ER_i32 e_idx     = 0;
        TAILQ_FOREACH(edge, &rel->gre_edges, ged_link) {
            ER_GraphEntity *e = edge->ged_entity;
            ER_i32          v = -1;

            // Strategy: 1. Try side closest to entity. 2. Try side with least
            // usage.
            if (e->gen_x + e->gen_w <= rel->gre_x && v_used[0] == 0) {
                v = 0;
            } else if (e->gen_x >= rel->gre_x + rel->gre_w && v_used[1] == 0) {
                v = 1;
            } else if (e->gen_y + e->gen_h <= rel->gre_y && v_used[2] == 0) {
                v = 2;
            } else if (e->gen_y >= rel->gre_y + rel->gre_h && v_used[3] == 0) {
                v = 3;
            } else { // Find least used
                ER_i32 min_u = v_used[0];
                v            = 0;
                for (ER_u8 i = 1; i < 4; i++) {
                    if (v_used[i] < min_u) {
                        min_u = v_used[i];
                        v     = i;
                    }
                }
            }
            v_used[v]++;

            switch (v) {
                case 0:
                    edge->ged_x1 = rel->gre_x;
                    edge->ged_y1 = rel->gre_y + rel->gre_h / 2;
                    break;

                case 1:
                    edge->ged_x1 = rel->gre_x + rel->gre_w;
                    edge->ged_y1 = rel->gre_y + rel->gre_h / 2;
                    break;

                case 2:
                    edge->ged_x1 = rel->gre_x + rel->gre_w / 2;
                    edge->ged_y1 = rel->gre_y;
                    break;

                case 3:
                    edge->ged_x1 = rel->gre_x + rel->gre_w / 2;
                    edge->ged_y1 = rel->gre_y + rel->gre_h;
                    break;

                default:
                    assert(!"invalid vertex");
            }

            // Distribute on Entity Surface
            if (e->gen_x + e->gen_w <= edge->ged_x1) { // Entity is left
                edge->ged_x2 = e->gen_x + e->gen_w;
                edge->ged_y2 = e->gen_y + 20 + (e_idx * 30) % (e->gen_h - 40);
            } else if (e->gen_x >= edge->ged_x1) { // Entity is right
                edge->ged_x2 = e->gen_x;
                edge->ged_y2 = e->gen_y + 20 + (e_idx * 30) % (e->gen_h - 40);
            } else if (e->gen_y + e->gen_h <= edge->ged_y1) { // Entity is above
                edge->ged_x2 = e->gen_x + 20 + (e_idx * 30) % (e->gen_w - 40);
                edge->ged_y2 = e->gen_y + e->gen_h;
            } else { // Entity is below
                edge->ged_x2 = e->gen_x + 20 + (e_idx * 30) % (e->gen_w - 40);
                edge->ged_y2 = e->gen_y;
            }
            e_idx++;
        }
    }
}
